---
- name: Развертывание веб-сайта о Audi RS7
  hosts: all
  become: yes

  tasks:
    - name: Установка Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Копирование HTML файла на веб-сервер
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Копирование изображений на веб-сервер
      copy:
        src: files/images/
        dest: /var/www/html/images/
        owner: www-data
        group: www-data
        mode: '0755'
        directory_mode: '0755'

    - name: Проверка конфигурации Nginx
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
