---
# tasks file for deploy_apache_web
   - name: Install NGINX
      apt:
        name: nginx
        state: present

   - name: Start and enable Nginx
       systemd:
        name: nginx
        state: started
        enabled: yes
   
   - name: Deploy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'
        owner: www-data
        group: www-data

